#!/usr/bin/env python3
"""Builds index.html (the website) from src/corpus.html (the app, identical to the claude.ai artifact).

The only difference is a block in <head> that loads the web runtime before the app starts:
config.js (Supabase project), vendor/supabase.js, web.js (window.claude on top of Supabase) and web.css,
plus home-screen icons. Each file gets ?v=<hash> so a new deploy is picked up right away.

    python3 build.py            # writes index.html
    python3 build.py --check    # fails if index.html is out of date
"""
import hashlib, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parent
SRC, OUT = ROOT / 'src' / 'corpus.html', ROOT / 'index.html'
MARK = '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">'


def v(path):
    return hashlib.sha256((ROOT / path).read_bytes()).hexdigest()[:10]


def build():
    src = SRC.read_text(encoding='utf8')
    assert src.count(MARK) == 1, 'viewport meta not found in src/corpus.html'
    head = '\n'.join([
        MARK,
        '<!-- web runtime: generated by build.py, not part of src/corpus.html -->',
        '<link rel="manifest" href="manifest.webmanifest">',
        '<link rel="icon" type="image/png" sizes="192x192" href="icons/icon-192.png">',
        '<link rel="apple-touch-icon" href="icons/apple-touch-icon.png">',
        '<meta name="apple-mobile-web-app-capable" content="yes">',
        '<meta name="mobile-web-app-capable" content="yes">',
        '<meta name="apple-mobile-web-app-title" content="Corpus">',
        '<meta name="apple-mobile-web-app-status-bar-style" content="default">',
        '<meta name="theme-color" content="#EDF0EE" media="(prefers-color-scheme: light)">',
        '<meta name="theme-color" content="#111614" media="(prefers-color-scheme: dark)">',
        f'<link rel="stylesheet" href="web.css?v={v("web.css")}">',
        f'<script src="config.js?v={v("config.js")}"></script>',
        f'<script src="vendor/supabase.js?v={v("vendor/supabase.js")}"></script>',
        f'<script src="web.js?v={v("web.js")}"></script>',
    ])
    return src.replace(MARK, head, 1)


if __name__ == '__main__':
    html = build()
    if '--check' in sys.argv:
        ok = OUT.exists() and OUT.read_text(encoding='utf8') == html
        print('index.html is up to date' if ok else 'index.html is OUT OF DATE: run python3 build.py')
        sys.exit(0 if ok else 1)
    OUT.write_text(html, encoding='utf8')
    print(f'wrote {OUT.name} ({len(html.encode()) // 1024} KB)')
